spring:
  application:
    name: streamline-logging-service.iml
  data:
    mongodb:
      uri: mongodb://streamline_mongo_user:streamline_mongo_pass@localhost:27017/streamline_logs?authSource=admin
      auto-index-creation: true
