spring:
  application:
    name: streamlime-api
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 65jfhoqi67coti65uddpk065q9 # fake
            client-secret: <client secret>
            scope:
              - openid
              - email
            redirect-uri: http://localhost:8080/api/v1/users/me # TO CHANGE
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_6Ri33hiZs # fake
            user-name-attribute: username
  datasource:
    url: ${POSTGRESQL_DB_URL:jdbc:postgresql://localhost:5432/streamline_db}
    username: ${POSTGRESQL_DB_USER:streamline_user}
    password: ${POSTGRESQL_DB_PASSWORD:streamline_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

#  docker run -d \
#  --name postgres \
#  -e POSTGRES_DB=streamline_db \
#  -e POSTGRES_USER=streamline_user \
#  -e POSTGRES_PASSWORD=streamline_pass \
#  -p 5432:5432 \
#  postgres:16

#  docker run -d \
#  --name mongo \
#  -e MONGO_INITDB_ROOT_USERNAME=streamline_mongo_user \
#  -e MONGO_INITDB_ROOT_PASSWORD=streamline_mongo_pass \
#  -p 27017:27017 \
#  mongo:7


# PROJECTS CONTAINERS
#  docker run -d \
#  --name streamlime-api \
#  -p 8080:8080 \
#  --link postgres:postgres \
#  --link mongo:mongo \
#  -e POSTGRESQL_DB_URL=jdbc:postgresql://postgres:5432/streamline_db \
#  -e POSTGRESQL_DB_USER=streamline_user \
#  -e POSTGRESQL_DB_PASSWORD=streamline_pass \
#  -e MONGO_CONNECTION_URL=mongodb://streamline_mongo_user:streamline_mongo_pass@mongo:27017/streamline_logs?authSource=admin \
#  streamlime-api
#
#  docker run -d \
#  --name streamline-logging-service \
#  -p 8081:8081 \
#  --link mongo:mongo \
#  -e MONGO_CONNECTION_URL=mongodb://streamline_mongo_user:streamline_mongo_pass@mongo:27017/streamline_logs?authSource=admin \
#  streamline-logging-service
